In [2]:
import numpy as np

In [3]:
test = np.array([[1000.0, 2.0], [1500.0, 3.0]])

In [4]:
def matrix_standardization(matrix):
    minimums = []
    maximums = []
    for column in matrix:
        min_value = column[0]
        max_value = column[0]
        for item in column:
            min_value = min(item, min_value)
            max_value = max(item, max_value)
        minimums.append(min_value)
        maximums.append(max_value)
    ranges = []
    for i in range(len(minimums)):
        ranges.append(maximums[i] - minimums[i])
    std_matrix = []
    for i in range(len(matrix)):
        std_col = []
        for item in matrix[i]:
            std_item = (item - minimums[i]) // ranges[i]
            std_col.append(std_item)
        std_matrix.append(std_col)
    return std_matrix

In [5]:
result = matrix_standardization(test)

In [6]:
result

[[1.0, 0.0], [1.0, 0.0]]

In [7]:
def milad_std(matrix):
    return (matrix - matrix.min(axis=0)) / (matrix.max(axis=0) - matrix.min(axis=0))

In [8]:
result = milad_std(test)

In [9]:
result

array([[0., 0.],
       [1., 1.]])

In [11]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(test)
print(test)

[[1000.    2.]
 [1500.    3.]]


In [12]:
def standard_s(X):
    return (X - X.mean(axis=0)) / X.std(axis=0)

In [14]:
result = standard_s(test)
result

array([[-1., -1.],
       [ 1.,  1.]])

In [16]:
standard_scaler = preprocessing.StandardScaler()
X_ss = standard_scaler.fit_transform(test)
X_ss

array([[-1., -1.],
       [ 1.,  1.]])